### ISSUE TITLE
マス目をクリックした時にマス目に○×を表示する機能の実装

### ISSUE THREAD

**Issue by pimon0807** [blueteam-recursion/tic-tac-toe#17]
### 概要
マス目をクリックした時にマス目に○×を表示する機能の実装

### 実装方法
各マス目のにクリックイベントを追加(createInitialBoardのarea.addEventListener内に追加すると簡単です)

##  タスク
Controller内に関数を作成
- Tableから現在が先行か後攻かを取得
- クリックされたマスのid情報を取得
- 取得した先行後攻情報とid情報を引数としたマスに○×を描画するView関数を実行
- Table.boardの配列内のデータを更新（○なら1,×なら-1を入力）
上記関数内で使用するView関数の作成
- idと先行後攻情報を受け取る
- 先行なら受け取ったidをもつマスに○をappend(良い丸のアイコンがなければ,最初はマスを赤色に変更で代用でも良いかもしれません)
- 後攻なら上記の×バージョン(上に合わせるなら,マスを青に変更とか?)

**Comment by Yoppiiii** [comment]
着手します！
よろしくお願いします！

**Comment by pimon0807** [comment]
了解です！

**Comment by fuji12345** [comment]
> 着手します！ よろしくお願いします！

了解です！
