### ISSUE TITLE
[Model]勝敗判定機能

### ISSUE THREAD

**Issue by pimon0807** [blueteam-recursion/tic-tac-toe#8]
### 概要
Tableの情報を元に縦、横、斜めのいずれかが同じマークになっているかを判別する関数

### 実装方法
2次元配列内の一列が同じになる集合を1つずつ判別する方法はどうでしょう
[
[1,2,3],
[4,5,6],
[7,8,9],
]
(1,2,3), (4,5,6), (7,8,9), (1,4,7), (2,5,8), (3,6,9), (1,5,9), (3,5,7)の組み合わせのうち1つに一致?

**Comment by pimon0807** [comment]
着手します。

**Comment by Yoppiiii** [comment]
> 着手します。

了解です！
