### ISSUE TITLE
ゲーム進行機能の実装

### ISSUE THREAD

**Issue by pimon0807** [blueteam-recursion/tic-tac-toe#9]
### 概要
3目並べのゲーム進行を管理する関数です

### 実装方法
Controller内に関数を作成
flagを持たせてゲームの進行を管理(勝敗判定関数がflagをFalseに変更できる)
各マス目のにクリックイベントを追加(createInitialBoardのarea.addEventListener内に追加すると簡単です)

## タスク
- 勝敗判別関数を実行 → 勝負終了ならflagをFalseに変えて結果画面へ
- 勝負継続ならboard内に0を持つ配列があるか確認 → なければ結果画面へ
- Table.turnの値を+1する
- #16 の関数を実行
- 以下繰り返し

**Comment by pimon0807** [comment]
着手します

**Comment by Yoppiiii** [comment]
> 着手します

了解です！
